using System;
using System.Collections.Generic;
using System.ComponentModel;
using CommunityToolkit.Mvvm.ComponentModel;

namespace AgyAccountSwarm.Services;

public interface ILocalizationService : INotifyPropertyChanged
{
    string CurrentLanguage { get; set; }
    void SetLanguage(string langCode);
    string this[string key] { get; }
    string Get(string key);
}

public partial class LocalizationService : ObservableObject, ILocalizationService
{
    public static LocalizationService Instance { get; } = new();

    [ObservableProperty]
    private string _currentLanguage = "en";

    private readonly Dictionary<string, string> _en = new(StringComparer.OrdinalIgnoreCase)
    {
        // Navigation
        ["Nav_Dashboard"] = "Dashboard",
        ["Nav_Accounts"] = "Accounts",
        ["Nav_RealtimeChat"] = "Real-Time Chat",
        ["Nav_RealtimeChat_Tip"] = "Real-Time Swarm & Agent Chat Messenger",
        ["Nav_Projects"] = "Swarm Worker",
        ["Nav_Analytics"] = "Analytics",
        ["Nav_Mcp"] = "MCP Tools",
        ["Nav_Docs"] = "Documentation",
        ["Nav_Logs"] = "Logs",
        ["Nav_Settings"] = "Settings",
        ["Nav_Skills"] = "Agent Skills",
        ["Nav_Terms"] = "Terms & Risk",
        ["Nav_About"] = "About",

        // Topbar
        ["App_Title"] = "Agy CLI Account Swarm",
        ["App_Subtitle"] = "Isolated multi-session manager, rate-limit monitor & quota tracker",
        ["App_BrandName"] = "Agy CLI Swarm",
        ["App_BrandRole"] = "Account Orchestrator",
        ["App_VersionBadge"] = "v0.9.8-beta",
        ["Btn_SyncSwarm"] = "Sync Accounts",
        ["Btn_LaunchSwarm"] = "Launch Swarm",
        ["Btn_StopSwarm"] = "Stop Swarm",
        ["Btn_CheckUpdates"] = "Check for Updates",
        ["Tag_SyncedJustNow"] = "Synced just now",
        ["Tag_SyncingAccounts"] = "Synchronizing Accounts...",
        ["Alert_QuotaExhausted"] = "Quota Exhausted Alert",
        ["Btn_Dismiss"] = "Dismiss",

        // Launch & Modes
        ["Launch_ConcurrentCli"] = "Concurrent Swarm CLI (Default)",
        ["Launch_WorkerOrchestration"] = "Swarm Worker Orchestration",
        ["Gradient_Theme"] = "Antigravity Gradient Theme",
        ["Worktree_SynthesizeAll"] = "Synthesize All Worktrees",
        ["Worktree_ConfirmTitle"] = "Confirm Worktree Synthesis & Branch Merge",
        ["Worktree_ConfirmDesc"] = "The Aggregator Hub will sequentially merge all worker branch contributions into the target branch.",
        ["Worktree_Proceed"] = "Proceed with Merge",
        ["Worktree_Cancel"] = "Cancel",

        // Sidebar
        ["Label_Sound"] = "Sound",
        ["Label_Theme"] = "Theme",
        ["Label_CliReady"] = "CLI Ready",
        ["Label_CliMissing"] = "CLI Missing",
        ["Label_SoundOn"] = "ON",
        ["Label_SoundMuted"] = "MUTED",

        // Dashboard 5 Metric Cards
        ["Card_TotalAccounts"] = "TOTAL PROFILES",
        ["Card_TotalAccounts_Sub"] = "Sandboxed accounts",
        ["Card_Authenticated"] = "AUTHENTICATED",
        ["Card_Authenticated_Sub"] = "Active Google credentials",
        ["Card_SwarmTargets"] = "SWARM WORKERS",
        ["Card_SwarmTargets_Sub"] = "Selected for execution",
        ["Card_ActiveSessions"] = "SAVED CONVERSATIONS",
        ["Card_ActiveSessions_Sub"] = "Historical chat sessions",
        ["Card_McpTools"] = "MCP TOOLS & SERVERS",
        ["Card_McpTools_Sub"] = "Protocol integrations",
        ["Card_TotalPrompts"] = "SAVED CONVERSATIONS",
        ["Card_TotalPrompts_Sub"] = "Historical chat sessions",
        ["Card_EstTokens"] = "MCP TOOLS & SERVERS",
        ["Card_EstTokens_Sub"] = "Protocol integrations",

        // Chart
        ["Chart_Title"] = "Prompt & Token Activity Distribution",
        ["Chart_Subtitle"] = "Real-time telemetry parsed from local history.jsonl and session logs",
        ["Chart_Filter_Account"] = "Account:",
        ["Chart_Filter_Period"] = "Period",
        ["Chart_Filter_Period_Label"] = "Period",
        ["Chart_Filter_Model"] = "Model",
        ["Chart_Filter_Model_Label"] = "Model",
        ["Chart_Filter_Tier"] = "Tier",
        ["Chart_Filter_Tier_Label"] = "Tier",
        ["Chart_Mode_Bar"] = "Bar",
        ["Chart_Mode_Line"] = "Line",
        ["Chart_Mode_Area"] = "Area",
        ["Chart_NoData"] = "No recorded prompt activity found in session history yet.",
        ["Chart_EmptySubtitle"] = "Switch account or timeframe filter above to view historical prompt sessions.",
        ["Chart_ZoomIn"] = "Zoom In",
        ["Chart_ZoomOut"] = "Zoom Out",

        // Accounts Actions & Labels
        ["Accounts_Header"] = "REGISTERED ACCOUNT PROFILES",
        ["Fleet_KPI_Header"] = "📊 FLEET KEY PERFORMANCE INDICATORS",
        ["Accounts_SearchPlaceholder"] = "Filter accounts by name, notes, email, model, or tier...",
        ["Accounts_SelectAll"] = "Select / Deselect All Swarm",
        ["Accounts_NewProfile"] = "New Profile",
        ["Accounts_Duplicate"] = "Duplicate",
        ["Accounts_EditProfile"] = "Edit Profile",
        ["Accounts_Delete"] = "Delete",
        ["Accounts_LaunchAgy"] = "▶ Launch agy",
        ["Accounts_StartConversation"] = "Start Conversation",
        ["Accounts_CopyCli"] = "Copy CLI",
        ["Accounts_Folder"] = "Open Folder",
        ["Accounts_PendingLogin"] = "Pending Login",
        ["Accounts_NotConnected"] = "Not Connected (Login Required)",
        ["Accounts_Velocity"] = "Velocity",
        ["Accounts_Headroom"] = "Headroom",
        ["Accounts_Role_Default"] = "Primary (Host Default)",
        ["Accounts_Role_Worker"] = "Isolated Sandbox Worker",
        ["Accounts_ActiveWorkersHeader"] = "Active Account Swarm Workers",
        ["Accounts_PrimaryDefault"] = "Primary Default",
        ["Accounts_SyncBadge"] = "Sync",
        ["Accounts_SwarmBadge"] = "Swarm",
        ["Accounts_SandboxLabel"] = "Sandbox:",
        ["Accounts_WorkspaceLabel"] = "Workspace:",
        ["Accounts_SuggestedSwitch"] = "Suggested: Switch to another swarm account",
        ["Accounts_VelocityHeader"] = "VELOCITY & DEPLETION FORECAST",
        ["Accounts_ResetLabel"] = "Reset:",
        ["Accounts_ModelQuotasHeader"] = "ANTIGRAVITY MODEL QUOTAS",
        ["Accounts_ModelQuotasSub"] = "Gemini, Claude & GPT Limits",
        ["Accounts_GeminiGroup"] = "GEMINI MODELS",
        ["Accounts_GeminiModels"] = "Flash, Pro",
        ["Accounts_GeminiDesc"] = "Models within this group: Gemini Flash, Gemini Pro",
        ["Accounts_WeeklyRemaining"] = "Weekly Limit Remaining",
        ["Accounts_FiveHourRemaining"] = "Five Hour Limit Remaining",
        ["Accounts_ClaudeGptGroup"] = "CLAUDE AND GPT MODELS",
        ["Accounts_ClaudeGptModels"] = "Opus, Sonnet, GPT-OSS",
        ["Accounts_ClaudeGptDesc"] = "Models within this group: Claude Opus, Claude Sonnet, GPT-OSS",
        ["Accounts_DocTitle"] = "PROFILE DOCTOR",
        ["Accounts_DocSubtitle"] = "CLI & Profile Diagnostics",
        ["Accounts_DocClear"] = "Clear",
        ["Accounts_DocStuckLocks"] = "Stuck Lock(s)",
        ["Accounts_DocTrust"] = "Register Workspace as Trusted",
        ["Accounts_AuthRequired"] = "Account Requires Authentication",
        ["Accounts_AuthRequiredDesc"] = "This sandbox profile has not completed Google Antigravity login. Authenticate to unlock CLI sessions, model quotas, and telemetry.",
        ["Accounts_BtnAuth"] = "Authenticate Account",
        ["Accounts_BtnCheckAuth"] = "Check Auth",
        ["Accounts_StartLabel"] = "Start:",
        ["Accounts_FilterPastConvs"] = "Type to filter past conversations...",
        ["Accounts_NoMatchingConvs"] = "No conversations match search query",
        ["Accounts_ImportChat"] = "Import Chat",
        ["Accounts_ChatRealtime"] = "💬 Chat Realtime",
        ["Accounts_ChatShortcutTooltip"] = "Open Real-Time Chat directly with this account",
        ["Accounts_ShortcutsHeader"] = "Shortcuts:",
        ["Accounts_ShortcutNew"] = "[Ctrl+N] New Profile",
        ["Accounts_ShortcutSearch"] = "[Ctrl+F] Search",
        ["Accounts_ShortcutRefresh"] = "[Ctrl+R] Refresh All",
        ["Accounts_ShortcutChat"] = "[Ctrl+Shift+C] Realtime Chat",
        ["Accounts_FiltersBtn"] = "Filters",
        ["Accounts_FilterModalTitle"] = "Filter & Sort Accounts",
        ["Accounts_ResetFilters"] = "Reset",
        ["Accounts_FilterTier"] = "Subscription Tier",
        ["Accounts_FilterHealth"] = "Status / Quota Health",
        ["Accounts_SortBy"] = "Sort By",

        // Profile Doctor
        ["Doctor_Title"] = "PROFILE DOCTOR",
        ["Doctor_Subtitle"] = "Audit AGY CLI Internal",
        ["Doctor_HealthCheck"] = "Health Check",
        ["Doctor_Checking"] = "Checking...",
        ["Doctor_CleanLocks"] = "Clean Stuck Locks",
        ["Doctor_TrustWorkspace"] = "Trust Workspace",
        ["Doctor_Clean"] = "Clean",
        ["Doctor_Warning"] = "Attention Required",

        // Swarm Multiplexer
        ["Swarm_Mux_Title"] = "Swarm Multi-Session Multiplexer",
        ["Swarm_Mux_Subtitle"] = "Execute automated workflows simultaneously across multiple sandboxed accounts. Compare different models in parallel.",
        ["Swarm_Mux_Layout"] = "Window Layout Mode",
        ["Swarm_Mux_FleetHeader"] = "Swarm Worker Fleet Selection",
        ["Swarm_Mux_FleetDesc"] = "Select which accounts participate in simultaneous multi-session terminal execution",
        ["Swarm_Mux_LaunchAll"] = "Launch Swarm for All Selected Accounts",
        ["Swarm_Concurrent_Title"] = "Concurrent Swarm Orchestrator",
        ["Swarm_Concurrent_Desc"] = "Launch multiple Antigravity AI accounts in parallel. Each session is completely isolated with its own credentials, workspace, and model quotas.",
        ["Swarm_Concurrent_LaunchMode"] = "Launch Mode:",
        ["Swarm_Concurrent_Active"] = "Swarm Active",
        ["Swarm_Concurrent_RunNow"] = "Run Swarm Now",
        ["Swarm_Concurrent_Stop"] = "Stop Swarm Execution",

        // Projects & Swarm Dispatcher
        ["Projects_Title"] = "Swarm Projects & Worker Dispatcher",
        ["Projects_Subtitle"] = "Organize multi-agent projects, branch sandboxes, and dispatch prompts",
        ["Projects_NewProject"] = "+ New Swarm Project",
        ["Projects_Tab_Feed"] = "Live Fleet Feed",
        ["Projects_Tab_Tasks"] = "Prompt Dispatch & Tasks",
        ["Projects_Tab_Worktree"] = "Git Worktree Tree",
        ["Projects_Tab_Topology"] = "Live Workflow Topology",
        ["Projects_EmptyTitle"] = "No Swarm Projects Configured",
        ["Projects_EmptyDesc"] = "To dispatch and orchestrate autonomous AI worker swarms, create a project context first. Each project isolates worktrees, task objectives, and agent chat telemetry.",
        ["Projects_CreateFirst"] = "Create First Swarm Project",
        ["Projects_SelectLabel"] = "Project:",
        ["Projects_EditProject"] = "Edit Project",
        ["Projects_OpenFolder"] = "Open Folder",
        ["Projects_DeleteProject"] = "Delete Project",
        ["Projects_ChatTitle"] = "Live Swarm Chat & Inter-Agent Message Bus",
        ["Projects_ChatSubtitle"] = "Synchronized real-time telemetry from .swarm/bus.jsonl, user broadcasts, and agent actions",
        ["Projects_ChatEmpty"] = "No messages recorded yet.",
        ["Projects_ChatEmptySub"] = "Dispatch the swarm or use the broadcast bar below to send instructions to the agents.",
        ["Projects_BroadcastPlaceholder"] = "Broadcast instruction to swarm workers...",
        ["Projects_BtnBroadcast"] = "Broadcast",
        ["Projects_SentinelsTitle"] = "Pre-flight Resource & Safety Sentinels",
        ["Projects_SentinelsSubtitle"] = "Hardware availability, storage limits, and Git Worktree capability checks",
        ["Projects_DiskSpace"] = "Disk Free Space",
        ["Projects_SystemMemory"] = "System Memory",
        ["Projects_GitStatus"] = "Git Repository Status",
        ["Projects_DispatchConfig"] = "Dispatch Configuration & Task Definition",
        ["Projects_TargetRepo"] = "Target Repository Directory:",
        ["Projects_TargetRepoPlaceholder"] = "Enter or paste absolute Git repository path (e.g. D:\\Works\\Project\\MyApp)...",
        ["Projects_BrowseFolder"] = "Browse Folder...",
        ["Projects_ExecutionMode"] = "Execution Mode:",
        ["Projects_QuickSuggestions"] = "Quick Objective Suggestions & Templates:",
        ["Projects_ObjectiveLabel"] = "Task Objective Prompt (Single Input -> Tailored Multi-Worker Execution):",
        ["Projects_ObjectivePlaceholder"] = "Describe the objective to accomplish (e.g. 'Implement a clean payment gateway webhook with signature validation, unit tests, and telemetry logging')...",
        ["Projects_WorkersFleet"] = "Participating Fleet Workers",
        ["Projects_WorkersFleetSub"] = "Workers selected below will receive tailored sub-task prompts in isolated environments",
        ["Projects_BtnDispatch"] = "Dispatch & Launch Swarm Fleet",
        ["Projects_BtnAbort"] = "Abort Fleet",
        ["Projects_BtnPrune"] = "Prune Worktrees",
        ["Projects_ActiveTasks"] = "Active Swarm Dispatch Tasks",
        ["Projects_ActiveTasksSub"] = "Real-time telemetry, active tool activities, and isolated workspace management",
        ["Projects_Activity"] = "Activity:",
        ["Projects_Output"] = "Output:",
        ["Projects_ConsoleLog"] = "Console Stream Log",
        ["Projects_WorktreeTreeTitle"] = "Git Worktree Branch Isolation Tree",
        ["Projects_WorktreeTreeSubtitle"] = "Live topological visualization of repository root and isolated worker branch sandboxes",
        ["Projects_RootRepo"] = "ROOT REPO",
        ["Projects_SharedStore"] = "Shared Object Store",
        ["Projects_SentinelsMatrixTitle"] = "Worktree Isolation Matrix & Sentinel Diagnostics",
        ["Projects_SentinelsMatrixSubtitle"] = "Deterministic boundary enforcement between concurrent git branch sandboxes",
        ["Projects_KeyringIsolation"] = "Keyring Isolation",
        ["Projects_KeyringDesc"] = "Zero auth bleed between worker sandboxes",
        ["Projects_FileLockGuard"] = "File Lock Guard",
        ["Projects_FileLockDesc"] = "Independent .git/index & HEAD per worker",
        ["Projects_PreflightChecks"] = "Preflight Checks",
        ["Projects_PreflightDesc"] = "Continuous disk & branch readiness audit",
        ["Projects_PruneSentinel"] = "Prune Sentinel",
        ["Projects_PruneDesc"] = "Auto-cleanup orphaned git worktrees",
        ["Projects_Topology_RosterTitle"] = "Registered Swarm Fleet",
        ["Projects_Topology_StandbyPrompt"] = "Click '🚀 Launch Swarm' to initiate parallel worker tasks",
        ["Projects_Topology_InterAgentBus"] = "Inter-Agent Bus",
        ["Projects_Topology_Blackboard"] = "Blackboard: Active Contracts",
        ["Projects_Topology_ReactiveStream"] = "Reactive Stream: Listening",
        ["Projects_Topology_GitTree"] = "Git Worktree Tree",
        ["Projects_Topology_ZeroLock"] = "Zero lock contention",

        // Real-Time Chat Studio
        ["Chat_Title"] = "Real-Time Swarm & Agent Chat Studio",
        ["Chat_Subtitle"] = "Live interactive inter-agent bus, direct-to-agent messaging, and telemetry stream",
        ["Chat_ChannelsHeader"] = "CHANNELS & AGENT ROSTER",
        ["Chat_BroadcastChannel"] = "📢 All Fleet Workers (Broadcast)",
        ["Chat_DirectChannel"] = "Direct Agent Channel",
        ["Chat_OnlineStatus"] = "Online & Ready",
        ["Chat_AwaitingStatus"] = "Awaiting Dispatch",
        ["Chat_TargetLabel"] = "Messaging Target:",
        ["Chat_InputPlaceholder"] = "Type message, goal, or command for agents... [Enter to send, Shift+Enter for new line]",
        ["Chat_BtnSend"] = "Send Message",
        ["Chat_ClearFeed"] = "Clear Chat",
        ["Chat_ExportTranscript"] = "Export Transcript",
        ["Chat_SuggestedPromptTitle"] = "Quick Agent Prompts & Directives:",
        ["Chat_SuggestedPrompt1"] = "🔍 Summarize current project architecture and readiness",
        ["Chat_SuggestedPrompt2"] = "🛡️ Perform a security and credential leakage audit",
        ["Chat_SuggestedPrompt3"] = "🧪 Check test suite coverage and generate missing unit tests",
        ["Chat_SuggestedPrompt4"] = "⚡ Check token consumption and burn-rate velocity",
        ["Chat_NoMessagesYet"] = "No messages recorded on this channel yet.",
        ["Chat_NoMessagesSub"] = "Send an instruction above or click a prompt suggestion to initiate real-time communication.",

        // Analytics
        ["Analytics_Title"] = "Swarm & Model Intelligence Telemetry",
        ["Analytics_Subtitle"] = "Deep breakdown of real token utilization, model efficiency, and quota health",
        ["Analytics_Recalculate"] = "Re-Calculate Telemetry",
        ["Analytics_ModelMatrix"] = "AI Model Performance & Efficiency Matrix",
        ["Analytics_HeatmapTitle"] = "24-Hour Swarm Execution Heatmap",
        ["Analytics_AccountHealth"] = "Swarm Fleet Intelligence & CLI Capabilities",
        ["Analytics_EstTokens"] = "EST. TOKENS",
        ["Analytics_EstTokens_Sub"] = "Total consumption",
        ["Analytics_InputTokens"] = "INPUT TOKENS",
        ["Analytics_InputTokens_Sub"] = "Prompts sent",
        ["Analytics_OutputTokens"] = "OUTPUT TOKENS",
        ["Analytics_OutputTokens_Sub"] = "AI completions",
        ["Analytics_AvgLatency"] = "AVG LATENCY",
        ["Analytics_AvgLatency_Sub"] = "Round-trip time",
        ["Analytics_UptimeSuccess"] = "UPTIME / SUCCESS",
        ["Analytics_UptimeSuccess_Sub"] = "Execution reliability",
        ["Analytics_SwarmStatus"] = "SWARM STATUS",
        ["Analytics_SwarmStatus_Sub"] = "Rate-limit safety",
        ["Analytics_TrendsTitle"] = "Real Telemetry Trends & Consumption",
        ["Analytics_TrendsSubtitle"] = "Multi-dimensional filtering across account sandboxes, LLM models, and authentic prompt activity",
        ["Analytics_NoActivity"] = "No Telemetry Activity Recorded",
        ["Analytics_NoActivitySub"] = "There are 0 prompt executions matching the selected account sandbox, model, and timeframe.",
        ["Analytics_EfficiencyTitle"] = "Model Efficiency Comparison Matrix",
        ["Analytics_EfficiencySubtitle"] = "Comparison of inference speed, token output, and error rates across all agy models",
        ["Analytics_ColModel"] = "MODEL",
        ["Analytics_ColRecommended"] = "RECOMMENDED",
        ["Analytics_ColRequests"] = "REQUESTS",
        ["Analytics_ColEstTokens"] = "EST. TOKENS",
        ["Analytics_ColAvgSpeed"] = "AVG SPEED",
        ["Analytics_ColErrorRate"] = "ERROR RATE",
        ["Analytics_ColStatus"] = "STATUS",
        ["Analytics_HeatmapSubtitle"] = "Actual timestamp frequency from local history files across all active instances",
        ["Analytics_FilterAccount"] = "Filter Account:",
        ["Analytics_PeakHour"] = "PEAK HOUR",
        ["Analytics_24hTurns"] = "24H TOTAL TURNS",
        ["Analytics_ActiveWindow"] = "ACTIVE WINDOW",
        ["Analytics_AvgHourlyRate"] = "AVG HOURLY RATE",
        ["Analytics_IntelligenceTitle"] = "Swarm Fleet Intelligence & CLI Capabilities",
        ["Analytics_IntelligenceSubtitle"] = "CLI model fleet orchestration, aggregate swarm pool capacity, and verified agy v1.2.12 capabilities",
        ["Analytics_CliEngineSync"] = "CLI v1.2.12 Engine Synchronized",
        ["Analytics_TotalPool"] = "TOTAL SWARM DAILY POOL",
        ["Analytics_TotalPoolSub"] = "Capacity across all active accounts",
        ["Analytics_PromptsToday"] = "SWARM PROMPTS TODAY",
        ["Analytics_BurnRate"] = "AGGREGATE BURN-RATE",
        ["Analytics_BurnRateSub"] = "Combined swarm burn-rate",
        ["Analytics_ExhaustionForecast"] = "SWARM EXHAUSTION FORECAST",
        ["Analytics_FleetModels"] = "Active Fleet Engine Models (agy models)",
        ["Analytics_ConnectedAccounts"] = "Connected accounts:",
        ["Analytics_VerifiedCapabilities"] = "Verified agy CLI Official Capabilities",
        ["Analytics_ExecutiveReports"] = "Executive Telemetry Reports",
        ["Analytics_ExecutiveReportsSub"] = "Export authentic logs, telemetry metrics, and agent turn history to PDF document or Excel spreadsheet",
        ["Analytics_BtnPdf"] = "Export Executive PDF",
        ["Analytics_BtnExcel"] = "Export Workbook (.xlsx)",
        ["Analytics_BtnRefresh"] = "Refresh Telemetry",

        // MCP
        ["Mcp_Title"] = "Model Context Protocol (MCP) Integrations",
        ["Mcp_Subtitle"] = "Manage external tool providers and context sidecars configured for Antigravity AI",
        ["Mcp_AddServer"] = "+ Add MCP Server",
        ["Mcp_Reload"] = "Reload MCPs",
        ["Mcp_ActiveServers"] = "Active MCP Servers",
        ["Mcp_ToolsCount"] = "Tools Discovered",

        // Skills
        ["Skills_Title"] = "Antigravity Agent Skills Catalog",
        ["Skills_Subtitle"] = "Discovered agent skills, prompt guidelines, and workflow extensions",
        ["Skills_SearchPlaceholder"] = "Search skills by name, description, tags, or source...",
        ["Skills_Reload"] = "Reload Skills",
        ["Skills_Folder"] = "Open Folder",
        ["Skills_Details"] = "View Details",

        // Docs
        ["Docs_Title"] = "Architecture & Technical Documentation",
        ["Docs_Subtitle"] = "Comprehensive reference for isolation, process workflows, and configuration options",
        ["Docs_ArchTitle"] = "System Architecture",
        ["Docs_ArchSub"] = "Process sandboxing, environment variable virtualization, and process tree architecture.",
        ["Docs_DoctorTitle"] = "Profile Doctor",
        ["Docs_DoctorSub"] = "5-checkpoint automated health audit, process lock cleaner, and workspace trust engine.",
        ["Docs_CliRefTitle"] = "CLI Reference",
        ["Docs_CliRefSub"] = "Antigravity CLI command mapping, 0-turn /usage extraction, and launcher scripts.",
        ["Docs_ChatMigrationTitle"] = "Chat Migration Guide",
        ["Docs_ChatMigrationSub"] = "Cross-account conversation transfer with 100% credential segregation.",
        ["Docs_SwarmWorkflowsTitle"] = "Swarm Workflows",
        ["Docs_SwarmWorkflowsSub"] = "Terminal multiplexing state machine, split-pane layout algorithms, and process lifecycle.",
        ["Docs_TroubleshootingTitle"] = "Troubleshooting",
        ["Docs_TroubleshootingSub"] = "10 common CLI initialization issues, BOM crash fixes, and lock resolutions.",
        ["Docs_RoadmapTitle"] = "Cross-Platform Roadmap",
        ["Docs_RoadmapSub"] = "Linux Wayland/X11 and macOS Metal feasibility and Avalonia UI migration roadmap.",
        ["Docs_TermsTitle"] = "Terms of Service & Risks",
        ["Docs_TermsSub"] = "Google Terms of Service, Generative AI policies, and developer safety principles.",

        // Logs
        ["Logs_Title"] = "Real-Time Execution Logs",
        ["Logs_Subtitle"] = "Authentic event bus, terminal orchestration output, and system diagnostics recorded daily",
        ["Logs_Refresh"] = "Refresh Logs",
        ["Logs_Clear"] = "Clear Buffer",
        ["Logs_Prune"] = "Prune Files (>7d)",
        ["Logs_OpenFolder"] = "Open Logs Folder",
        ["Logs_Export"] = "Export Workbook (.xlsx)",

        // Settings
        ["Settings_Title"] = "Application Settings & Preferences",
        ["Settings_Subtitle"] = "Configure terminal execution paths, swarm orchestration defaults, and system integration.",
        ["Settings_Language"] = "Display Language",
        ["Settings_TerminalGroup"] = "Terminal Launcher & Window Layout",
        ["Settings_TrayGroup"] = "Background & System Tray Integration",
        ["Settings_AudioGroup"] = "Audio Feedback & Sound Synthesizer",
        ["Settings_WelcomeGroup"] = "Cat Welcome Startup Animation",
        ["Settings_AboutGroup"] = "About & Open Source Credits",
        ["Settings_StorageGroup"] = "Storage, Profiles & Data Maintenance",
        ["Settings_AutoSyncGroup"] = "Periodic Swarm & MCP Auto-Sync",
        ["Settings_ExecutionGroup"] = "Swarm Execution & Launch Action",

        // Terms
        ["Terms_Title"] = "Terms of Service & Risk Disclosure",
        ["Terms_Subtitle"] = "Legal boundaries, operational safety, LLM rate limits, and sandboxing architecture",

        // About
        ["About_Title"] = "Agy CLI Account Swarm",
        ["About_Subtitle"] = "Version 0.9.8-beta • Avalonia Cross-Platform Edition",
        ["About_Updates_Title"] = "Software Updates & Version Stream",

        // Modals & General
        ["Modal_Worktree_Title"] = "Confirm Worktree Synthesis (Git Merge)",
        ["Modal_Worktree_Subtitle"] = "Synthesizing parallel worker branches into base repository",
        ["Modal_Worktree_Warning"] = "⚠️ Attention: Aggregator Sequential Merge",
        ["Modal_Worktree_Confirm"] = "🔀 Confirm & Synthesize All",
        ["Modal_Cancel"] = "Cancel",
        ["Modal_Save"] = "Save",
        ["Modal_Close"] = "Close",

        // Profile Edit Window
        ["Edit_Title"] = "Profile Configuration & Archetype",
        ["Edit_Subtitle"] = "Configure sandbox isolation, swarm execution role, preferred models, and color tags",
        ["Edit_DisplayName"] = "Profile Display Name *",
        ["Edit_DisplayNamePlaceholder"] = "e.g. Worker Alpha, Lead Architect, Security Auditor",
        ["Edit_Role"] = "Swarm Execution Role / Archetype",
        ["Edit_RoleNotes"] = "Role Description / Responsibility Notes",
        ["Edit_RoleNotesPlaceholder"] = "Brief notes or role assignment specifications",
        ["Edit_ModelSection"] = "Preferred AI Model & Reasoning Parameters",
        ["Edit_ModelFamily"] = "Model Provider Family",
        ["Edit_Preset"] = "Reasoning & Temperature Preset",
        ["Edit_ModelId"] = "Target Model Identifier",
        ["Edit_Workspace"] = "Default Project Workspace",
        ["Edit_CustomDir"] = "Custom Isolated Profile Directory (Optional)",
        ["Edit_SkipPerms"] = "--dangerously-skip-permissions",
        ["Edit_SkipPermsDesc"] = "Bypasses interactive CLI confirmation prompts for tool use, file edits, and terminal execution during automated swarm loops",
        ["Edit_VisualSection"] = "Visual Accent & Swarm Participation",
        ["Edit_ColorPreset"] = "Color Palette Preset",
        ["Edit_CustomHex"] = "Custom HEX Code",
        ["Edit_Preview"] = "Preview",
        ["Edit_BtnCancel"] = "Cancel",
        ["Edit_BtnSave"] = "Save Configuration",

        // Topology
        ["Topology_Title"] = "⚡ Real-Time Swarm Workflow Topology",
        ["Topology_Subtitle"] = "Visual execution graph & live agent node pipeline — inspired by n8n workflow architecture tailored for autonomous agy-cli agents.",
        ["Topology_Trigger"] = "PROJECT TRIGGER",
        ["Topology_Workers"] = "WORKER POOL (STANDBY)",
        ["Topology_Aggregator"] = "AGGREGATOR HUB",
        ["Topology_Output"] = "OUTPUT SYNTHESIS",
        ["Topology_Dispatch"] = "⚡ Dispatch",
        ["Topology_Telemetry"] = "📡 Telemetry",
        ["Topology_Branches"] = "🌿 Branches",
        ["Topology_ViewBlackboard"] = "📋 View Blackboard",
        ["Topology_InspectTree"] = "🌳 Inspect Tree",
        ["Tag_AutoSyncActive"] = "SUCCESS • AUTO-SYNC ACTIVE",
        ["Tag_AutoSyncOff"] = "PAUSED • AUTO-SYNC OFF",
        ["Btn_ExportPdf"] = "Export PDF Dossier",

        // Additional Dispatcher & Worktree Keys
        ["Projects_BtnCheckResources"] = "🔍 Check Resources",
        ["Projects_ModeTerminal"] = "🖥️ Visible Terminal Windows",
        ["Projects_ModeHeadless"] = "⚡ Silent Background (Headless)",
        ["Projects_AutoApprove"] = "Auto-approve tool permissions (--dangerously-skip-permissions)",
        ["Projects_IsolateWorktrees"] = "Isolate workers in linked Git Worktrees (.worktrees/worker-*) to avoid .git/index.lock contention",
        ["Projects_SelectAllWorkers"] = "☑️ Select All",
        ["Projects_CopyLog"] = "📋 Copy Full Log",
        ["Projects_BtnFolder"] = "📂 Folder",
        ["Projects_BtnMerge"] = "🔀 Merge",
        ["Projects_BtnStopWorker"] = "🛑 Stop Worker",
        ["Projects_ActiveGuards"] = "ACTIVE GUARDS • 4 SENTINELS",
        ["Projects_DefaultBadge"] = "Default",
        ["Projects_QuickAction"] = "🚀 Quick Action:",
        ["Projects_QuickActionDesc"] = "Provision a new sandbox repository context or clone worktrees",

        // Topology Additional Keys
        ["Topology_ReactivePipeline"] = "REACTIVE PIPELINE",
        ["Topology_TriggerOnDispatch"] = "⚡ Trigger: On Dispatch",
        ["Topology_SynthesizeAll"] = "🔀 Synthesize Worktrees",

        // Real-Time Chat Studio Additional Keys
        ["Chat_Blackboard"] = "Blackboard",
        ["Chat_TipSend"] = "Tip: Shift+Enter for newline, Enter to send",
        ["Chat_CopyMessage"] = "Copy message text",
        ["Chat_SimultaneousDispatch"] = "Simultaneous dispatch to all workers",
        ["Chat_DirectWorkersHeader"] = "DIRECT AGENT WORKERS",

        // Docs Additional Keys
        ["Docs_FleetTitle"] = "Fleet Prompt Dispatcher [EXP]",
        ["Docs_FleetSub"] = "Git worktree orchestration, multi-worker prompt dispersion, and out-of-resources handling.",
        ["Docs_OpenSpec"] = "🌐 Open Spec in Browser",

        // Logs Additional Keys
        ["Logs_SearchPlaceholder"] = "Search logs by keyword, exception, message, timestamp...",
        ["Logs_LevelFilter"] = "Level Filter:",
        ["Logs_ColTimestamp"] = "TIMESTAMP",
        ["Logs_ColLevel"] = "LEVEL",
        ["Logs_ColMessage"] = "DIAGNOSTIC LOG MESSAGE",
        ["Logs_EmptyTitle"] = "🔍 No matching log entries found.",
        ["Logs_EmptySub"] = "Adjust your search query or log level filter, or click 'Refresh' to re-read files.",

        // Settings Additional Keys
        ["Settings_LanguageSub"] = "Select your preferred application display language.",
        ["Settings_ThemeTitle"] = "Theme Appearance & Color Palette",
        ["Settings_ThemeSub"] = "Choose your preferred color palette. Surface contrasts, glowing badges, and borders are mathematically calibrated for maximum readability across Windows, Linux, and macOS.",
        ["Settings_ThemeSystem"] = "🖥️ System (Auto OS)",
        ["Settings_ThemeSystemSub"] = "Syncs with OS dark/light mode",
        ["Settings_ThemeDark"] = "🌙 Obsidian Dark",
        ["Settings_ThemeDarkSub"] = "Deep midnight navy with electric cyan",
        ["Settings_ThemeLight"] = "☀️ Daylight Clean",
        ["Settings_ThemeLightSub"] = "Crisp white surface with cerulean blue",
        ["Settings_ThemeCyber"] = "🔮 Cyberpunk Neon",
        ["Settings_ThemeCyberSub"] = "Neon pink, ultraviolet & cyber blue",
        ["Settings_ThemeMatrix"] = "📟 Matrix Emerald",
        ["Settings_ThemeMatrixSub"] = "Terminal phosphor green with CRT glow",
        ["Settings_PrefTerminal"] = "Preferred Terminal Emulator",
        ["Settings_PrefTerminalSub"] = "Select which console window launches the isolated agy sessions.",
        ["Settings_SwarmArrangement"] = "Swarm Window Arrangement",
        ["Settings_SwarmArrangementSub"] = "Choose how multiple parallel workers are arranged when Launch Swarm is clicked.",
        ["Settings_AgyBinary"] = "Antigravity CLI Binary Path",
        ["Settings_AgyBinarySub"] = "Automatically discovered or custom path to the 'agy' executable.",
        ["Settings_ExecutionSub"] = "Customize the Launch Swarm action behavior, Antigravity gradient accent themes, and worktree synthesis workflow.",
        ["Settings_LaunchActionMode"] = "Swarm Launch Action Mode:",
        ["Settings_ConcurrentModeSub"] = "Directly spawns all isolated account terminals simultaneously",
        ["Settings_WorkerFleetSub"] = "Orchestrates workers with prompt dispersion & worktree isolation",
        ["Settings_GradientThemeTitle"] = "Antigravity Gradient Accent Theme:",
        ["Settings_GradientThemeSub"] = "Select the color harmony applied to the Launch Swarm button and visual highlights:",
        ["Settings_NavbarMode"] = "Top Navigation Bar Layout Mode:",
        ["Settings_NavbarModeSub"] = "Detailed shows full telemetry badges; Minimalist preserves screen width.",
        ["Settings_WorktreeConfirm"] = "Git Worktree Synthesis Confirmation:",
        ["Settings_WorktreeConfirmSub"] = "Show confirmation alert modal before synthesizing / merging all worker git worktrees",
        ["Settings_CloseBehavior"] = "Window Close [✕] Behavior",
        ["Settings_CloseBehaviorSub"] = "Choose what happens when the titlebar close button [✕] is clicked.",
        ["Settings_CloseTray"] = "📥 Minimize to System Tray",
        ["Settings_CloseTraySub"] = " (Runs silently in background with tray icon & periodic sync)",
        ["Settings_CloseExit"] = "🛑 Exit Application Completely",
        ["Settings_CloseExitSub"] = " (Closes all background threads and terminates swarm immediately)",
        ["Settings_MinBehavior"] = "Window Minimize [🗕] Behavior",
        ["Settings_MinBehaviorSub"] = "Minimize button [🗕] hides window to system tray instead of taskbar",
        ["Settings_SoundTx"] = "Enable synthesized audio tones on user transactions (clicks, launches, chimes)",
        ["Settings_SoundWelcome"] = "Play calm ambient welcome chime (~3s) on application startup / splash screen",
        ["Settings_SoundSync"] = "Play subtle droplet chime when periodic auto-sync completes in background",
        ["Settings_SoundTest"] = "Test Sound Effects:",
        ["Settings_SoundTestWelcome"] = "🔔 Calm Welcome Chime (3s)",
        ["Settings_SoundTestAlert"] = "🚨 Quota Exhausted Alert",
        ["Settings_SoundTestSync"] = "🔄 Sync Droplet Chime",
        ["Settings_AboutDesc"] = "Agy CLI Account Swarm is a high-performance, open-source orchestration tool for Google Antigravity CLI users.",
        ["Settings_AboutCreated"] = "Created & Maintained by:",
        ["Settings_AboutLicense"] = "Licensed under MIT License — Open for community contributions & portfolio showcase.",
        ["Settings_AutoSyncSub"] = "Automatically recalculate real token consumption, probe active model presence, and scan MCP tool servers in the background.",
        ["Settings_AutoSyncToggle"] = "Enable background automatic telemetry synchronization loop",
        ["Settings_AutoSyncInterval"] = "Auto-Sync Interval:",
        ["Settings_StorageSub"] = "Profiles and application settings are persisted in local app data:",
        ["Settings_StorageBtnAppData"] = "Open AppData Folder",
        ["Settings_StorageBtnAppLog"] = "Open Application Log",
        ["Settings_UpdatesSub"] = "Check against the official GitHub release repository for new features, bugfixes, and model support.",

        // Project Dialog Modal
        ["ProjectDialog_Subtitle"] = "Configure workspace roots, default tech stack, and assign participating worker profiles",
        ["ProjectDialog_NameLabel"] = "Project Name:",
        ["ProjectDialog_DescLabel"] = "Project Purpose & Description:",
        ["ProjectDialog_StackLabel"] = "Target Tech Stack:",
        ["ProjectDialog_BranchLabel"] = "Default Base Branch:",
        ["ProjectDialog_RootDirLabel"] = "Project Root Directory:",
        ["ProjectDialog_BrowseBtn"] = "📁 Browse Folder...",
        ["ProjectDialog_WorktreesToggle"] = "Enable Git Worktree Branch Isolation for workers",
        ["ProjectDialog_ObjectiveLabel"] = "Default Swarm Objective (Optional Template):",
        ["ProjectDialog_WorkersLabel"] = "Assigned Worker Accounts:",
        ["ProjectDialog_SaveBtn"] = "💾 Save Project",

        // Worktree Synthesis Modal
        ["Modal_Worktree_Explain"] = "You are about to merge all active worker branches sequentially into the primary branch. Make sure worker processes have finished writing files to prevent merge conflicts.",
        ["Modal_Worktree_TargetRepo"] = "TARGET REPOSITORY",
        ["Modal_Worktree_BranchesToSynth"] = "BRANCHES TO SYNTHESIZE",
        ["Modal_Worktree_BranchesQueued"] = "Worker Branches Queued for Synthesis:",
        ["Modal_Worktree_Ready"] = "Ready to Merge",
        ["Modal_Worktree_AlwaysAsk"] = "Always ask for confirmation before worktree synthesis (can change in Settings)",

        // Skill Details Modal
        ["SkillModal_Location"] = "📁 Location: ",
        ["SkillModal_PromptHeader"] = "SKILL.md System Prompt Instructions:",

        // Splash Screen
        ["Splash_Title"] = "Google Antigravity CLI Swarm",
        ["Splash_Subtitle"] = "Multi-Account Sandbox Orchestrator & Telemetry Fleet",
        ["Splash_Initializing"] = "Initializing Fleet & Quota Telemetry...",
    };

    private readonly Dictionary<string, string> _id = new(StringComparer.OrdinalIgnoreCase)
    {
        // Navigation
        ["Nav_Dashboard"] = "Dasbor",
        ["Nav_Accounts"] = "Akun Swarm",
        ["Nav_RealtimeChat"] = "Chat Realtime",
        ["Nav_RealtimeChat_Tip"] = "Pengirim Pesan & Obrolan Realtime Armada Swarm",
        ["Nav_Projects"] = "Swarm & Pekerja",
        ["Nav_Analytics"] = "Analitik",
        ["Nav_Mcp"] = "Alat MCP",
        ["Nav_Docs"] = "Dokumentasi",
        ["Nav_Logs"] = "Catatan Log",
        ["Nav_Settings"] = "Pengaturan",
        ["Nav_Skills"] = "Keahlian Agen (Skills)",
        ["Nav_Terms"] = "Ketentuan & Risiko",
        ["Nav_About"] = "Tentang",

        // Topbar
        ["App_Title"] = "Agy CLI Account Swarm",
        ["App_Subtitle"] = "Manajer multi-sesi terisolasi, pemantau rate-limit & pelacak kuota",
        ["App_BrandName"] = "Agy CLI Swarm",
        ["App_BrandRole"] = "Orkestrator Akun",
        ["App_VersionBadge"] = "v0.9.8-beta",
        ["Btn_SyncSwarm"] = "Sinkron Akun",
        ["Btn_LaunchSwarm"] = "Jalankan Swarm",
        ["Btn_StopSwarm"] = "Hentikan Swarm",
        ["Btn_CheckUpdates"] = "Periksa Pembaruan",
        ["Tag_SyncedJustNow"] = "Baru saja disinkronkan",
        ["Tag_SyncingAccounts"] = "Menyinkronkan Akun...",
        ["Alert_QuotaExhausted"] = "Peringatan Kuota Habis",
        ["Btn_Dismiss"] = "Tutup",

        // Launch & Modes
        ["Launch_ConcurrentCli"] = "CLI Swarm Serentak (Default)",
        ["Launch_WorkerOrchestration"] = "Orkestrasi Pekerja Swarm",
        ["Gradient_Theme"] = "Tema Gradien Antigravity",
        ["Worktree_SynthesizeAll"] = "Satukan Semua Worktree",
        ["Worktree_ConfirmTitle"] = "Konfirmasi Penyatuan Worktree & Penggabungan Cabang",
        ["Worktree_ConfirmDesc"] = "Hub Agregator akan menggabungkan seluruh kontribusi cabang pekerja ke dalam cabang target secara berurutan.",
        ["Worktree_Proceed"] = "Lanjutkan Penyatuan",
        ["Worktree_Cancel"] = "Batal",

        // Sidebar
        ["Label_Sound"] = "Suara",
        ["Label_Theme"] = "Tema",
        ["Label_CliReady"] = "CLI Siap",
        ["Label_CliMissing"] = "CLI Hilang",
        ["Label_SoundOn"] = "AKTIF",
        ["Label_SoundMuted"] = "SENYAP",

        // Dashboard 5 Metric Cards
        ["Card_TotalAccounts"] = "TOTAL PROFIL",
        ["Card_TotalAccounts_Sub"] = "Akun terisolasi",
        ["Card_Authenticated"] = "TERAUTENTIKASI",
        ["Card_Authenticated_Sub"] = "Kredensial Google aktif",
        ["Card_SwarmTargets"] = "PEKERJA SWARM",
        ["Card_SwarmTargets_Sub"] = "Dipilih untuk eksekusi",
        ["Card_ActiveSessions"] = "SESI PERCAKAPAN",
        ["Card_ActiveSessions_Sub"] = "Riwayat chat tersimpan",
        ["Card_McpTools"] = "ALAT & SERVER MCP",
        ["Card_McpTools_Sub"] = "Integrasi protokol",
        ["Card_TotalPrompts"] = "SESI PERCAKAPAN",
        ["Card_TotalPrompts_Sub"] = "Riwayat chat tersimpan",
        ["Card_EstTokens"] = "ALAT & SERVER MCP",
        ["Card_EstTokens_Sub"] = "Integrasi protokol",

        // Chart
        ["Chart_Title"] = "Distribusi Aktivitas Prompt & Token",
        ["Chart_Subtitle"] = "Telemetri real-time diambil dari berkas riwayat history.jsonl & log",
        ["Chart_Filter_Account"] = "Akun:",
        ["Chart_Filter_Period"] = "Periode",
        ["Chart_Filter_Period_Label"] = "Periode",
        ["Chart_Filter_Model"] = "Model",
        ["Chart_Filter_Model_Label"] = "Model",
        ["Chart_Filter_Tier"] = "Tier",
        ["Chart_Filter_Tier_Label"] = "Tier",
        ["Chart_Mode_Bar"] = "Batang",
        ["Chart_Mode_Line"] = "Garis",
        ["Chart_Mode_Area"] = "Area",
        ["Chart_NoData"] = "Belum ada riwayat aktivitas prompt yang tercatat di sesi ini.",
        ["Chart_EmptySubtitle"] = "Ganti filter akun atau rentang waktu di atas untuk melihat riwayat sesi prompt.",
        ["Chart_ZoomIn"] = "Perbesar",
        ["Chart_ZoomOut"] = "Perkecil",

        // Accounts Actions & Labels
        ["Accounts_Header"] = "PROFIL AKUN TERDAFTAR",
        ["Fleet_KPI_Header"] = "📊 INDIKATOR KINERJA UTAMA ARMADA",
        ["Accounts_SearchPlaceholder"] = "Cari profil berdasarkan nama, catatan, email, model, atau tier...",
        ["Accounts_SelectAll"] = "Pilih / Batalkan Semua Swarm",
        ["Accounts_NewProfile"] = "Tambah Profil",
        ["Accounts_Duplicate"] = "Duplikat",
        ["Accounts_EditProfile"] = "Edit Profil",
        ["Accounts_Delete"] = "Hapus",
        ["Accounts_LaunchAgy"] = "▶ Buka agy",
        ["Accounts_StartConversation"] = "Mulai Percakapan",
        ["Accounts_CopyCli"] = "Salin CLI",
        ["Accounts_Folder"] = "Buka Folder",
        ["Accounts_PendingLogin"] = "Belum Login",
        ["Accounts_NotConnected"] = "Belum Terhubung (Perlu Login)",
        ["Accounts_Velocity"] = "Kecepatan",
        ["Accounts_Headroom"] = "Kapasitas Sisa",
        ["Accounts_Role_Default"] = "Utama (Host Default)",
        ["Accounts_Role_Worker"] = "Worker Sandbox Terisolasi",
        ["Accounts_ActiveWorkersHeader"] = "Pekerja Swarm Akun Aktif",
        ["Accounts_PrimaryDefault"] = "Default Utama",
        ["Accounts_SyncBadge"] = "Sinkron",
        ["Accounts_SwarmBadge"] = "Swarm",
        ["Accounts_SandboxLabel"] = "Sandbox:",
        ["Accounts_WorkspaceLabel"] = "Ruang Kerja:",
        ["Accounts_SuggestedSwitch"] = "Disarankan: Beralih ke akun swarm lain",
        ["Accounts_VelocityHeader"] = "PERKIRAAN KECEPATAN & PENYUSUTAN",
        ["Accounts_ResetLabel"] = "Reset:",
        ["Accounts_ModelQuotasHeader"] = "KUOTA MODEL ANTIGRAVITY",
        ["Accounts_ModelQuotasSub"] = "Batas Gemini, Claude & GPT",
        ["Accounts_GeminiGroup"] = "MODEL GEMINI",
        ["Accounts_GeminiModels"] = "Flash, Pro",
        ["Accounts_GeminiDesc"] = "Model dalam grup ini: Gemini Flash, Gemini Pro",
        ["Accounts_WeeklyRemaining"] = "Sisa Batas Mingguan",
        ["Accounts_FiveHourRemaining"] = "Sisa Batas Lima Jam",
        ["Accounts_ClaudeGptGroup"] = "MODEL CLAUDE DAN GPT",
        ["Accounts_ClaudeGptModels"] = "Opus, Sonnet, GPT-OSS",
        ["Accounts_ClaudeGptDesc"] = "Model dalam grup ini: Claude Opus, Claude Sonnet, GPT-OSS",
        ["Accounts_DocTitle"] = "DOKTER PROFIL",
        ["Accounts_DocSubtitle"] = "Diagnostik CLI & Profil",
        ["Accounts_DocClear"] = "Bersihkan",
        ["Accounts_DocStuckLocks"] = "Lock Macet",
        ["Accounts_DocTrust"] = "Daftarkan Ruang Kerja Terpercaya",
        ["Accounts_AuthRequired"] = "Akun Memerlukan Autentikasi",
        ["Accounts_AuthRequiredDesc"] = "Profil sandbox ini belum menyelesaikan login Google Antigravity. Lakukan autentikasi untuk membuka sesi CLI, kuota model, dan telemetri.",
        ["Accounts_BtnAuth"] = "Autentikasi Akun",
        ["Accounts_BtnCheckAuth"] = "Cek Autentikasi",
        ["Accounts_StartLabel"] = "Mulai:",
        ["Accounts_FilterPastConvs"] = "Ketik untuk menyaring percakapan lampau...",
        ["Accounts_NoMatchingConvs"] = "Tidak ada percakapan yang cocok dengan pencarian",
        ["Accounts_ImportChat"] = "Impor Percakapan",
        ["Accounts_ChatRealtime"] = "💬 Chat Realtime",
        ["Accounts_ChatShortcutTooltip"] = "Buka Chat Realtime langsung dengan akun ini",
        ["Accounts_ShortcutsHeader"] = "Pintasan:",
        ["Accounts_ShortcutNew"] = "[Ctrl+N] Profil Baru",
        ["Accounts_ShortcutSearch"] = "[Ctrl+F] Cari",
        ["Accounts_ShortcutRefresh"] = "[Ctrl+R] Segarkan Semua",
        ["Accounts_ShortcutChat"] = "[Ctrl+Shift+C] Chat Realtime",
        ["Accounts_FiltersBtn"] = "Filter",
        ["Accounts_FilterModalTitle"] = "Filter & Urutkan Akun",
        ["Accounts_ResetFilters"] = "Reset",
        ["Accounts_FilterTier"] = "Tier Langganan",
        ["Accounts_FilterHealth"] = "Kesehatan Status / Kuota",
        ["Accounts_SortBy"] = "Urutkan Berdasarkan",

        // Profile Doctor
        ["Doctor_Title"] = "DOKTER PROFIL",
        ["Doctor_Subtitle"] = "Audit Jeroan AGY CLI",
        ["Doctor_HealthCheck"] = "Periksa Kesehatan",
        ["Doctor_Checking"] = "Memeriksa...",
        ["Doctor_CleanLocks"] = "Bersihkan Lock File",
        ["Doctor_TrustWorkspace"] = "Daftarkan Workspace",
        ["Doctor_Clean"] = "Bersih",
        ["Doctor_Warning"] = "Perlu Tindakan",

        // Swarm Multiplexer
        ["Swarm_Mux_Title"] = "Multiplekser Multi-Sesi Swarm",
        ["Swarm_Mux_Subtitle"] = "Jalankan alur kerja otomatis secara serentak di beberapa akun terisolasi. Bandingkan berbagai model secara paralel.",
        ["Swarm_Mux_Layout"] = "Mode Tata Letak Jendela",
        ["Swarm_Mux_FleetHeader"] = "Pemilihan Armada Pekerja Swarm",
        ["Swarm_Mux_FleetDesc"] = "Pilih akun mana yang berpartisipasi dalam eksekusi terminal multi-sesi serentak",
        ["Swarm_Mux_LaunchAll"] = "Jalankan Swarm untuk Semua Akun Terpilih",
        ["Swarm_Concurrent_Title"] = "Orkestrator Swarm Serentak",
        ["Swarm_Concurrent_Desc"] = "Jalankan banyak akun Antigravity AI secara paralel. Setiap sesi terisolasi penuh dengan kredensial, ruang kerja, dan kuota model masing-masing.",
        ["Swarm_Concurrent_LaunchMode"] = "Mode Peluncuran:",
        ["Swarm_Concurrent_Active"] = "Swarm Aktif",
        ["Swarm_Concurrent_RunNow"] = "Jalankan Swarm Sekarang",
        ["Swarm_Concurrent_Stop"] = "Hentikan Eksekusi Swarm",

        // Projects & Swarm Dispatcher
        ["Projects_Title"] = "Proyek Swarm & Orkestrator Pekerja",
        ["Projects_Subtitle"] = "Kelola proyek multi-agen, sandbox cabang, dan dispersi prompt",
        ["Projects_NewProject"] = "+ Proyek Swarm Baru",
        ["Projects_Tab_Feed"] = "Siaran Langsung Armada",
        ["Projects_Tab_Tasks"] = "Dispersi Prompt & Tugas",
        ["Projects_Tab_Worktree"] = "Pohon Git Worktree",
        ["Projects_Tab_Topology"] = "Topologi Alur Kerja Langsung",
        ["Projects_EmptyTitle"] = "Belum Ada Proyek Swarm",
        ["Projects_EmptyDesc"] = "Untuk mendispersi dan mengorkestrasi swarm pekerja AI otonom, buat konteks proyek terlebih dahulu. Setiap proyek mengisolasi worktree, target tugas, dan telemetri chat agen.",
        ["Projects_CreateFirst"] = "Buat Proyek Swarm Pertama",
        ["Projects_SelectLabel"] = "Proyek:",
        ["Projects_EditProject"] = "Edit Proyek",
        ["Projects_OpenFolder"] = "Buka Folder",
        ["Projects_DeleteProject"] = "Hapus Proyek",
        ["Projects_ChatTitle"] = "Obrolan Swarm Langsung & Bus Pesan Antar-Agen",
        ["Projects_ChatSubtitle"] = "Telemetri real-time tersinkronisasi dari .swarm/bus.jsonl, siaran pengguna, dan tindakan agen",
        ["Projects_ChatEmpty"] = "Belum ada pesan tercatat.",
        ["Projects_ChatEmptySub"] = "Jalankan swarm atau gunakan bilah siaran di bawah untuk mengirim instruksi ke para agen.",
        ["Projects_BroadcastPlaceholder"] = "Kirim instruksi siaran ke seluruh pekerja swarm...",
        ["Projects_BtnBroadcast"] = "Kirim Siaran",
        ["Projects_SentinelsTitle"] = "Sentinel Keamanan & Sumber Daya Pra-Peluncuran",
        ["Projects_SentinelsSubtitle"] = "Pemeriksaan ketersediaan perangkat keras, batas penyimpanan, dan kapabilitas Git Worktree",
        ["Projects_DiskSpace"] = "Ruang Bebas Hard Disk",
        ["Projects_SystemMemory"] = "Memori Sistem (RAM)",
        ["Projects_GitStatus"] = "Status Repositori Git",
        ["Projects_DispatchConfig"] = "Konfigurasi Dispersi & Definisi Tugas",
        ["Projects_TargetRepo"] = "Direktori Repositori Target:",
        ["Projects_TargetRepoPlaceholder"] = "Ketik atau tempel path absolut repositori Git (contoh: D:\\Works\\Project\\MyApp)...",
        ["Projects_BrowseFolder"] = "Jelajahi Folder...",
        ["Projects_ExecutionMode"] = "Mode Eksekusi:",
        ["Projects_QuickSuggestions"] = "Saran Target Cepat & Templat:",
        ["Projects_ObjectiveLabel"] = "Prompt Target Tugas (Satu Input -> Eksekusi Mandiri Multi-Pekerja):",
        ["Projects_ObjectivePlaceholder"] = "Deskripsikan target yang ingin dicapai (misal: 'Implementasikan webhook gateway pembayaran dengan validasi tanda tangan, unit test, dan pencatatan log telemetri')...",
        ["Projects_WorkersFleet"] = "Pekerja Armada yang Berpartisipasi",
        ["Projects_WorkersFleetSub"] = "Pekerja yang dipilih di bawah akan menerima prompt tugas khusus di lingkungan terisolasi",
        ["Projects_BtnDispatch"] = "Dispersi & Luncurkan Armada Swarm",
        ["Projects_BtnAbort"] = "Batalkan Armada",
        ["Projects_BtnPrune"] = "Pangkas Worktree",
        ["Projects_ActiveTasks"] = "Tugas Dispersi Swarm Aktif",
        ["Projects_ActiveTasksSub"] = "Telemetri real-time, aktivitas perkakas aktif, dan manajemen ruang kerja terisolasi",
        ["Projects_Activity"] = "Aktivitas:",
        ["Projects_Output"] = "Keluaran (Output):",
        ["Projects_ConsoleLog"] = "Log Aliran Konsol",
        ["Projects_WorktreeTreeTitle"] = "Pohon Isolasi Cabang Git Worktree",
        ["Projects_WorktreeTreeSubtitle"] = "Visualisasi topologis langsung dari akar repositori dan cabang sandbox pekerja terisolasi",
        ["Projects_RootRepo"] = "REPOSITORI AKAR",
        ["Projects_SharedStore"] = "Penyimpanan Objek Bersama",
        ["Projects_SentinelsMatrixTitle"] = "Matriks Isolasi Worktree & Diagnostik Sentinel",
        ["Projects_SentinelsMatrixSubtitle"] = "Penegakan batas deterministik antar sandbox cabang git serentak",
        ["Projects_KeyringIsolation"] = "Isolasi Kredensial",
        ["Projects_KeyringDesc"] = "Nol kebocoran autentikasi antar sandbox pekerja",
        ["Projects_FileLockGuard"] = "Pengaman Lock Berkas",
        ["Projects_FileLockDesc"] = "Independen .git/index & HEAD untuk setiap pekerja",
        ["Projects_PreflightChecks"] = "Pemeriksaan Pra-Terbang",
        ["Projects_PreflightDesc"] = "Audit kesiapan disk & cabang secara berkala",
        ["Projects_PruneSentinel"] = "Sentinel Pembersihan",
        ["Projects_PruneDesc"] = "Pembersihan otomatis cabang git worktree yatim",
        ["Projects_Topology_RosterTitle"] = "Armada Swarm Terdaftar",
        ["Projects_Topology_StandbyPrompt"] = "Klik '🚀 Luncurkan Swarm' untuk memulai tugas pekerja paralel",
        ["Projects_Topology_InterAgentBus"] = "Bus Antar-Agen",
        ["Projects_Topology_Blackboard"] = "Blackboard: Kontrak Aktif",
        ["Projects_Topology_ReactiveStream"] = "Aliran Reaktif: Mendengarkan",
        ["Projects_Topology_GitTree"] = "Pohon Git Worktree",
        ["Projects_Topology_ZeroLock"] = "Bebas konflik lock berkas",

        // Real-Time Chat Studio
        ["Chat_Title"] = "Studio Obrolan Realtime Swarm & Agen",
        ["Chat_Subtitle"] = "Bus inter-agen langsung, perpesanan langsung ke agen, dan aliran telemetri",
        ["Chat_ChannelsHeader"] = "SALURAN & DAFTAR AGEN",
        ["Chat_BroadcastChannel"] = "📢 Seluruh Armada Pekerja (Siaran)",
        ["Chat_DirectChannel"] = "Saluran Agen Langsung",
        ["Chat_OnlineStatus"] = "Online & Siap",
        ["Chat_AwaitingStatus"] = "Menunggu Tugas",
        ["Chat_TargetLabel"] = "Target Pesan:",
        ["Chat_InputPlaceholder"] = "Ketik pesan, target, atau perintah untuk agen... [Enter untuk kirim, Shift+Enter untuk baris baru]",
        ["Chat_BtnSend"] = "Kirim Pesan",
        ["Chat_ClearFeed"] = "Bersihkan Chat",
        ["Chat_ExportTranscript"] = "Ekspor Transkrip",
        ["Chat_SuggestedPromptTitle"] = "Prompt & Instruksi Agen Cepat:",
        ["Chat_SuggestedPrompt1"] = "🔍 Ringkas arsitektur proyek saat ini dan kesiapan",
        ["Chat_SuggestedPrompt2"] = "🛡️ Jalankan audit keamanan dan kebocoran kredensial",
        ["Chat_SuggestedPrompt3"] = "🧪 Periksa cakupan pengujian dan buat unit test yang kurang",
        ["Chat_SuggestedPrompt4"] = "⚡ Periksa konsumsi token dan kecepatan penggunaan",
        ["Chat_NoMessagesYet"] = "Belum ada pesan yang tercatat di saluran ini.",
        ["Chat_NoMessagesSub"] = "Kirimkan instruksi di atas atau klik salah satu saran prompt untuk memulai komunikasi langsung.",

        // Analytics
        ["Analytics_Title"] = "Telemetri Intelijen Swarm & Model",
        ["Analytics_Subtitle"] = "Analisis mendalam konsumsi token riil, efisiensi model, dan kesehatan kuota",
        ["Analytics_Recalculate"] = "Hitung Ulang Telemetri",
        ["Analytics_ModelMatrix"] = "Matriks Kinerja & Efisiensi Model AI",
        ["Analytics_HeatmapTitle"] = "Peta Intensitas Eksekusi Swarm 24-Jam",
        ["Analytics_AccountHealth"] = "Armada Model & Kapabilitas agy CLI",
        ["Analytics_EstTokens"] = "EST. TOKEN",
        ["Analytics_EstTokens_Sub"] = "Total konsumsi",
        ["Analytics_InputTokens"] = "TOKEN INPUT",
        ["Analytics_InputTokens_Sub"] = "Prompt terkirim",
        ["Analytics_OutputTokens"] = "TOKEN OUTPUT",
        ["Analytics_OutputTokens_Sub"] = "Penyelesaian AI",
        ["Analytics_AvgLatency"] = "RATA-RATA LATENSI",
        ["Analytics_AvgLatency_Sub"] = "Waktu bolak-balik",
        ["Analytics_UptimeSuccess"] = "UPTIME / KEBERHASILAN",
        ["Analytics_UptimeSuccess_Sub"] = "Keandalan eksekusi",
        ["Analytics_SwarmStatus"] = "STATUS SWARM",
        ["Analytics_SwarmStatus_Sub"] = "Keamanan rate-limit",
        ["Analytics_TrendsTitle"] = "Tren & Konsumsi Telemetri Riil",
        ["Analytics_TrendsSubtitle"] = "Penyaringan multi-dimensi di berbagai sandbox akun, model LLM, dan aktivitas prompt autentik",
        ["Analytics_NoActivity"] = "Tidak Ada Aktivitas Telemetri Tercatat",
        ["Analytics_NoActivitySub"] = "Ada 0 eksekusi prompt yang cocok dengan sandbox akun, model, dan rentang waktu terpilih.",
        ["Analytics_EfficiencyTitle"] = "Matriks Perbandingan Efisiensi Model",
        ["Analytics_EfficiencySubtitle"] = "Perbandingan kecepatan inferensi, output token, dan tingkat kesalahan di seluruh model agy",
        ["Analytics_ColModel"] = "MODEL",
        ["Analytics_ColRecommended"] = "DISARANKAN",
        ["Analytics_ColRequests"] = "PERMINTAAN",
        ["Analytics_ColEstTokens"] = "EST. TOKEN",
        ["Analytics_ColAvgSpeed"] = "RATA-RATA KECEPATAN",
        ["Analytics_ColErrorRate"] = "TINGKAT KESALAHAN",
        ["Analytics_ColStatus"] = "STATUS",
        ["Analytics_HeatmapSubtitle"] = "Frekuensi cap waktu aktual dari riwayat lokal di seluruh instans aktif",
        ["Analytics_FilterAccount"] = "Filter Akun:",
        ["Analytics_PeakHour"] = "JAM TERTINGGI",
        ["Analytics_24hTurns"] = "TOTAL TURN 24 JAM",
        ["Analytics_ActiveWindow"] = "JENDELA AKTIF",
        ["Analytics_AvgHourlyRate"] = "RATA-RATA PER JAM",
        ["Analytics_IntelligenceTitle"] = "Intelijen Armada Swarm & Kapabilitas CLI",
        ["Analytics_IntelligenceSubtitle"] = "Orkestrasi model armada CLI, kapasitas gabungan swarm, dan verifikasi kapabilitas agy v1.2.12 capabilities",
        ["Analytics_CliEngineSync"] = "Mesin CLI v1.2.12 Tersinkronisasi",
        ["Analytics_TotalPool"] = "TOTAL KUOTA HARIAN SWARM",
        ["Analytics_TotalPoolSub"] = "Kapasitas di seluruh akun aktif",
        ["Analytics_PromptsToday"] = "PROMPT SWARM HARI INI",
        ["Analytics_BurnRate"] = "KECEPATAN KONSUMSI GABUNGAN",
        ["Analytics_BurnRateSub"] = "Laju konsumsi gabungan armada",
        ["Analytics_ExhaustionForecast"] = "PERKIRAAN HABISNYA KUOTA SWARM",
        ["Analytics_FleetModels"] = "Model Mesin Armada Aktif (agy models)",
        ["Analytics_ConnectedAccounts"] = "Akun terhubung:",
        ["Analytics_VerifiedCapabilities"] = "Kapabilitas Resmi Terverifikasi agy CLI",
        ["Analytics_ExecutiveReports"] = "Laporan Telemetri Eksekutif",
        ["Analytics_ExecutiveReportsSub"] = "Ekspor log autentik, metrik telemetri, dan riwayat giliran agen ke dokumen PDF atau lembar sebar Excel",
        ["Analytics_BtnPdf"] = "Ekspor PDF Eksekutif",
        ["Analytics_BtnExcel"] = "Ekspor Buku Kerja (.xlsx)",
        ["Analytics_BtnRefresh"] = "Segarkan Telemetri",

        // MCP
        ["Mcp_Title"] = "Integrasi Model Context Protocol (MCP)",
        ["Mcp_Subtitle"] = "Kelola penyedia tools eksternal dan sidecar context untuk Antigravity AI",
        ["Mcp_AddServer"] = "+ Tambah Server MCP",
        ["Mcp_Reload"] = "Muat Ulang MCP",
        ["Mcp_ActiveServers"] = "Server MCP Aktif",
        ["Mcp_ToolsCount"] = "Alat Ditemukan",

        // Skills
        ["Skills_Title"] = "Katalog Keahlian Agen (Skills)",
        ["Skills_Subtitle"] = "Keahlian agen terdeteksi, panduan prompt, dan ekstensi alur kerja",
        ["Skills_SearchPlaceholder"] = "Cari keahlian berdasarkan nama, deskripsi, tag, atau sumber...",
        ["Skills_Reload"] = "Muat Ulang Keahlian",
        ["Skills_Folder"] = "Buka Folder",
        ["Skills_Details"] = "Lihat Detail",

        // Docs
        ["Docs_Title"] = "Arsitektur & Dokumentasi Teknis",
        ["Docs_Subtitle"] = "Panduan lengkap isolasi direktori, alur kerja proses, dan konfigurasi",
        ["Docs_ArchTitle"] = "Arsitektur Sistem",
        ["Docs_ArchSub"] = "Sandbox proses, virtualisasi variabel lingkungan, dan arsitektur hierarki proses.",
        ["Docs_DoctorTitle"] = "Dokter Profil",
        ["Docs_DoctorSub"] = "Audit kesehatan 5 titik otomatis, pembersih lock proses, dan mesin registrasi ruang kerja.",
        ["Docs_CliRefTitle"] = "Referensi CLI",
        ["Docs_CliRefSub"] = "Pemetaan perintah Antigravity CLI, ekstraksi /usage tanpa turn, dan skrip peluncur.",
        ["Docs_ChatMigrationTitle"] = "Panduan Migrasi Obrolan",
        ["Docs_ChatMigrationSub"] = "Pemindahan percakapan antar akun dengan 100% segregasi kredensial.",
        ["Docs_SwarmWorkflowsTitle"] = "Alur Kerja Swarm",
        ["Docs_SwarmWorkflowsSub"] = "Mesin status multipleks terminal, algoritma tata letak terbagi, dan daur hidup proses.",
        ["Docs_TroubleshootingTitle"] = "Pemecahan Masalah",
        ["Docs_TroubleshootingSub"] = "10 masalah inisialisasi CLI umum, perbaikan crash BOM, dan resolusi lock.",
        ["Docs_RoadmapTitle"] = "Peta Jalan Lintas Platform",
        ["Docs_RoadmapSub"] = "Kelayakan Linux Wayland/X11 & macOS Metal serta peta jalan migrasi UI Avalonia.",
        ["Docs_TermsTitle"] = "Ketentuan Layanan & Risiko",
        ["Docs_TermsSub"] = "Ketentuan Layanan Google, kebijakan AI Generatif, dan prinsip keselamatan developer.",

        // Logs
        ["Logs_Title"] = "Catatan Log Eksekusi Real-Time",
        ["Logs_Subtitle"] = "Event bus autentik, output orkestrasi terminal, dan diagnostik sistem tercatat harian",
        ["Logs_Refresh"] = "Segarkan Log",
        ["Logs_Clear"] = "Bersihkan Buffer",
        ["Logs_Prune"] = "Pangkas Berkas (>7hr)",
        ["Logs_OpenFolder"] = "Buka Folder Log",
        ["Logs_Export"] = "Ekspor Buku Kerja (.xlsx)",

        // Settings
        ["Settings_Title"] = "Pengaturan & Preferensi Aplikasi",
        ["Settings_Subtitle"] = "Atur launcher terminal, default orkestrator swarm, bahasa, dan integrasi sistem tray.",
        ["Settings_Language"] = "Bahasa Tampilan",
        ["Settings_TerminalGroup"] = "Launcher Terminal & Tata Letak Jendela",
        ["Settings_TrayGroup"] = "Integrasi Background & System Tray",
        ["Settings_AudioGroup"] = "Umpan Balik Audio & Efek Suara",
        ["Settings_WelcomeGroup"] = "Animasi Sapaan Kucing",
        ["Settings_AboutGroup"] = "Tentang & Kontributor Open Source",
        ["Settings_StorageGroup"] = "Penyimpanan, Profil & Pemeliharaan Data",
        ["Settings_AutoSyncGroup"] = "Sinkronisasi Otomatis Swarm & MCP Berkala",
        ["Settings_ExecutionGroup"] = "Eksekusi Swarm & Aksi Peluncuran",

        // Terms
        ["Terms_Title"] = "Ketentuan Layanan & Keterbukaan Risiko",
        ["Terms_Subtitle"] = "Batasan hukum, keselamatan operasional, batasan kuota LLM, dan arsitektur sandbox",

        // About
        ["About_Title"] = "Agy CLI Account Swarm",
        ["About_Subtitle"] = "Versi 0.9.8-beta • Edisi Lintas Platform Avalonia",
        ["About_Updates_Title"] = "Pembaruan Perangkat Lunak & Aliran Versi",

        // Modals & General
        ["Modal_Worktree_Title"] = "Konfirmasi Penyatuan Worktree (Git Merge)",
        ["Modal_Worktree_Subtitle"] = "Menyatukan cabang pekerja paralel ke dalam repositori utama",
        ["Modal_Worktree_Warning"] = "⚠️ Perhatian: Penyatuan Sekuensial Agregator",
        ["Modal_Worktree_Confirm"] = "🔀 Konfirmasi & Satukan Semua",
        ["Modal_Cancel"] = "Batal",
        ["Modal_Save"] = "Simpan",
        ["Modal_Close"] = "Tutup",

        // Profile Edit Window
        ["Edit_Title"] = "Konfigurasi & Arketipe Profil",
        ["Edit_Subtitle"] = "Atur isolasi sandbox, peran eksekusi swarm, model preferensi, dan warna aksen",
        ["Edit_DisplayName"] = "Nama Tampilan Profil *",
        ["Edit_DisplayNamePlaceholder"] = "mis. Worker Alpha, Arsitek Utama, Auditor Keamanan",
        ["Edit_Role"] = "Peran Eksekusi Swarm / Arketipe",
        ["Edit_RoleNotes"] = "Catatan Deskripsi Peran / Tanggung Jawab",
        ["Edit_RoleNotesPlaceholder"] = "Catatan singkat atau spesifikasi tugas peran",
        ["Edit_ModelSection"] = "Model AI Pilihan & Parameter Penalaran",
        ["Edit_ModelFamily"] = "Famili Penyedia Model",
        ["Edit_Preset"] = "Preset Penalaran & Temperatur",
        ["Edit_ModelId"] = "Pengenal Model Target (Model ID)",
        ["Edit_Workspace"] = "Ruang Kerja Proyek Bawaan",
        ["Edit_CustomDir"] = "Direktori Profil Terisolasi Kustom (Opsional)",
        ["Edit_SkipPerms"] = "--dangerously-skip-permissions",
        ["Edit_SkipPermsDesc"] = "Melewati prompt konfirmasi interaktif CLI untuk perkakas, edit berkas, dan eksekusi terminal saat loop swarm otomatis",
        ["Edit_VisualSection"] = "Aksen Visual & Partisipasi Swarm",
        ["Edit_ColorPreset"] = "Pilihan Palet Warna",
        ["Edit_CustomHex"] = "Kode HEX Kustom",
        ["Edit_Preview"] = "Pratinjau",
        ["Edit_BtnCancel"] = "Batal",
        ["Edit_BtnSave"] = "Simpan Konfigurasi",

        // Topology
        ["Topology_Title"] = "⚡ Topologi Alur Kerja Swarm Real-Time",
        ["Topology_Subtitle"] = "Grafik eksekusi visual & pipeline node agen langsung — terinspirasi arsitektur alur kerja n8n untuk agen agy-cli otonom.",
        ["Topology_Trigger"] = "PEMICU PROYEK",
        ["Topology_Workers"] = "KUMPULAN PEKERJA (STANDBY)",
        ["Topology_Aggregator"] = "HUB AGREGATOR",
        ["Topology_Output"] = "SINTESIS OUTPUT",
        ["Topology_Dispatch"] = "⚡ Dispersi",
        ["Topology_Telemetry"] = "📡 Telemetry",
        ["Topology_Branches"] = "🌿 Cabang",
        ["Topology_ViewBlackboard"] = "📋 Lihat Blackboard",
        ["Topology_InspectTree"] = "🌳 Periksa Pohon",
        ["Tag_AutoSyncActive"] = "SUKSES • AUTO-SYNC AKTIF",
        ["Tag_AutoSyncOff"] = "JEDA • AUTO-SYNC NONAKTIF",
        ["Btn_ExportPdf"] = "Ekspor Berkas PDF",

        // Additional Dispatcher & Worktree Keys
        ["Projects_BtnCheckResources"] = "🔍 Periksa Sumber Daya",
        ["Projects_ModeTerminal"] = "🖥️ Jendela Terminal Terlihat",
        ["Projects_ModeHeadless"] = "⚡ Latar Belakang Senyap (Headless)",
        ["Projects_AutoApprove"] = "Setujui otomatis izin perkakas (--dangerously-skip-permissions)",
        ["Projects_IsolateWorktrees"] = "Isolasi pekerja dalam Git Worktree (.worktrees/worker-*) untuk cegah konflik .git/index.lock",
        ["Projects_SelectAllWorkers"] = "☑️ Pilih Semua",
        ["Projects_CopyLog"] = "📋 Salin Log Lengkap",
        ["Projects_BtnFolder"] = "📂 Folder",
        ["Projects_BtnMerge"] = "🔀 Gabungkan",
        ["Projects_BtnStopWorker"] = "🛑 Hentikan Pekerja",
        ["Projects_ActiveGuards"] = "PENJAGA AKTIF • 4 SENTINEL",
        ["Projects_DefaultBadge"] = "Default",
        ["Projects_QuickAction"] = "🚀 Aksi Cepat:",
        ["Projects_QuickActionDesc"] = "Siapkan konteks repositori sandbox baru atau klon worktree",

        // Topology Additional Keys
        ["Topology_ReactivePipeline"] = "PIPELINE REAKTIF",
        ["Topology_TriggerOnDispatch"] = "⚡ Pemicu: Saat Dispersi",
        ["Topology_SynthesizeAll"] = "🔀 Satukan Worktree",

        // Real-Time Chat Studio Additional Keys
        ["Chat_Blackboard"] = "Papan Tulis (Blackboard)",
        ["Chat_TipSend"] = "Tip: Shift+Enter untuk baris baru, Enter untuk kirim",
        ["Chat_CopyMessage"] = "Salin teks pesan",
        ["Chat_SimultaneousDispatch"] = "Dispersi serentak ke seluruh pekerja",
        ["Chat_DirectWorkersHeader"] = "PEKERJA AGEN LANGSUNG",

        // Docs Additional Keys
        ["Docs_FleetTitle"] = "Disperser Prompt Armada [EXP]",
        ["Docs_FleetSub"] = "Orkestrasi Git worktree, dispersi prompt multi-pekerja, dan penanganan kehabisan sumber daya.",
        ["Docs_OpenSpec"] = "🌐 Buka Spesifikasi di Browser",

        // Logs Additional Keys
        ["Logs_SearchPlaceholder"] = "Cari log berdasarkan kata kunci, pengecualian, pesan, cap waktu...",
        ["Logs_LevelFilter"] = "Filter Tingkat:",
        ["Logs_ColTimestamp"] = "CAP WAKTU",
        ["Logs_ColLevel"] = "TINGKAT",
        ["Logs_ColMessage"] = "PESAN LOG DIAGNOSTIK",
        ["Logs_EmptyTitle"] = "🔍 Tidak ditemukan catatan log yang cocok.",
        ["Logs_EmptySub"] = "Sesuaikan kata kunci pencarian atau filter tingkat log, atau klik 'Segarkan' untuk membaca ulang berkas.",

        // Settings Additional Keys
        ["Settings_LanguageSub"] = "Pilih bahasa tampilan aplikasi pilihan Anda.",
        ["Settings_ThemeTitle"] = "Tampilan Tema & Palet Warna",
        ["Settings_ThemeSub"] = "Pilih palet warna pilihan Anda. Kontras permukaan, lencana menyala, dan garis batas dikalibrasi secara matematis untuk keterbacaan optimal di Windows, Linux, dan macOS.",
        ["Settings_ThemeSystem"] = "🖥️ Sistem (Otomatis OS)",
        ["Settings_ThemeSystemSub"] = "Menyesuaikan mode gelap/terang OS",
        ["Settings_ThemeDark"] = "🌙 Obsidian Gelap",
        ["Settings_ThemeDarkSub"] = "Biru dongker pekat dengan sian elektrik",
        ["Settings_ThemeLight"] = "☀️ Daylight Terang",
        ["Settings_ThemeLightSub"] = "Permukaan putih bersih dengan biru serulean",
        ["Settings_ThemeCyber"] = "🔮 Cyberpunk Neon",
        ["Settings_ThemeCyberSub"] = "Merah muda neon, ultraviolet & biru siber",
        ["Settings_ThemeMatrix"] = "📟 Matrix Zamrud",
        ["Settings_ThemeMatrixSub"] = "Hijau fosfor terminal dengan kilau CRT",
        ["Settings_PrefTerminal"] = "Emulator Terminal Pilihan",
        ["Settings_PrefTerminalSub"] = "Pilih jendela konsol mana yang meluncurkan sesi agy terisolasi.",
        ["Settings_SwarmArrangement"] = "Tata Letak Jendela Swarm",
        ["Settings_SwarmArrangementSub"] = "Pilih bagaimana beberapa pekerja paralel diatur saat Luncurkan Swarm diklik.",
        ["Settings_AgyBinary"] = "Lokasi Berkas Biner Antigravity CLI",
        ["Settings_AgyBinarySub"] = "Lokasi otomatis atau jalur khusus ke berkas eksekusi 'agy'.",
        ["Settings_ExecutionSub"] = "Sesuaikan perilaku aksi Luncurkan Swarm, tema aksen gradien Antigravity, dan alur kerja penyatuan worktree.",
        ["Settings_LaunchActionMode"] = "Mode Aksi Peluncuran Swarm:",
        ["Settings_ConcurrentModeSub"] = "Meluncurkan seluruh terminal akun terisolasi secara serentak",
        ["Settings_WorkerFleetSub"] = "Mengorkestrasi pekerja dengan dispersi prompt & isolasi worktree",
        ["Settings_GradientThemeTitle"] = "Tema Aksen Gradien Antigravity:",
        ["Settings_GradientThemeSub"] = "Pilih keselarasan warna untuk tombol Luncurkan Swarm dan sorotan visual:",
        ["Settings_NavbarMode"] = "Mode Tata Letak Bilah Navigasi Atas:",
        ["Settings_NavbarModeSub"] = "Detail menampilkan lencana telemetri lengkap; Minimalis menghemat lebar layar.",
        ["Settings_WorktreeConfirm"] = "Konfirmasi Penyatuan Git Worktree:",
        ["Settings_WorktreeConfirmSub"] = "Tampilkan modal konfirmasi sebelum menyatukan / menggabungkan seluruh git worktree pekerja",
        ["Settings_CloseBehavior"] = "Perilaku Tombol Tutup Jendela [✕]",
        ["Settings_CloseBehaviorSub"] = "Pilih apa yang terjadi saat tombol tutup [✕] di bilah judul diklik.",
        ["Settings_CloseTray"] = "📥 Minimalkan ke System Tray",
        ["Settings_CloseTraySub"] = " (Berjalan senyap di latar belakang dengan ikon baki & sinkronisasi berkala)",
        ["Settings_CloseExit"] = "🛑 Keluar dari Aplikasi Sepenuhnya",
        ["Settings_CloseExitSub"] = " (Menutup semua utas latar belakang dan menghentikan swarm segera)",
        ["Settings_MinBehavior"] = "Perilaku Tombol Minimalkan Jendela [🗕]",
        ["Settings_MinBehaviorSub"] = "Tombol minimalkan [🗕] menyembunyikan jendela ke system tray bukan taskbar",
        ["Settings_SoundTx"] = "Aktifkan nada audio sintetis pada interaksi pengguna (klik, peluncuran, denting)",
        ["Settings_SoundWelcome"] = "Putar denting sapaan ambient tenang (~3dtk) saat pembukaan aplikasi",
        ["Settings_SoundSync"] = "Putar denting tetesan lembut saat sinkronisasi otomatis selesai di latar belakang",
        ["Settings_SoundTest"] = "Uji Efek Suara:",
        ["Settings_SoundTestWelcome"] = "🔔 Denting Sapaan Tenang (3dtk)",
        ["Settings_SoundTestAlert"] = "🚨 Peringatan Kuota Habis",
        ["Settings_SoundTestSync"] = "🔄 Denting Tetesan Sinkron",
        ["Settings_AboutDesc"] = "Agy CLI Account Swarm adalah alat orkestrasi berkinerja tinggi dan bersumber terbuka untuk pengguna Google Antigravity CLI.",
        ["Settings_AboutCreated"] = "Dibuat & Dikelola oleh:",
        ["Settings_AboutLicense"] = "Berlisensi di bawah Lisensi MIT — Terbuka untuk kontribusi komunitas & pameran portofolio.",
        ["Settings_AutoSyncSub"] = "Hitung ulang konsumsi token riil secara otomatis, uji ketersediaan model aktif, dan pindai server alat MCP di latar belakang.",
        ["Settings_AutoSyncToggle"] = "Aktifkan loop sinkronisasi telemetri otomatis di latar belakang",
        ["Settings_AutoSyncInterval"] = "Interval Sinkronisasi Otomatis:",
        ["Settings_StorageSub"] = "Profil dan pengaturan aplikasi disimpan di app data lokal:",
        ["Settings_StorageBtnAppData"] = "Buka Folder AppData",
        ["Settings_StorageBtnAppLog"] = "Buka Log Aplikasi",
        ["Settings_UpdatesSub"] = "Periksa repositori rilis resmi GitHub untuk fitur baru, perbaikan bug, dan dukungan model.",

        // Project Dialog Modal
        ["ProjectDialog_Subtitle"] = "Konfigurasikan direktori kerja, tech stack bawaan, dan tetapkan profil pekerja yang berpartisipasi",
        ["ProjectDialog_NameLabel"] = "Nama Proyek:",
        ["ProjectDialog_DescLabel"] = "Tujuan & Deskripsi Proyek:",
        ["ProjectDialog_StackLabel"] = "Tech Stack Target:",
        ["ProjectDialog_BranchLabel"] = "Cabang Dasar Bawaan:",
        ["ProjectDialog_RootDirLabel"] = "Direktori Utama Proyek:",
        ["ProjectDialog_BrowseBtn"] = "📁 Jelajahi Folder...",
        ["ProjectDialog_WorktreesToggle"] = "Aktifkan Isolasi Cabang Git Worktree untuk para pekerja",
        ["ProjectDialog_ObjectiveLabel"] = "Target Bawaan Swarm (Templat Opsional):",
        ["ProjectDialog_WorkersLabel"] = "Akun Pekerja yang Ditugaskan:",
        ["ProjectDialog_SaveBtn"] = "💾 Simpan Proyek",

        // Worktree Synthesis Modal
        ["Modal_Worktree_Explain"] = "Anda akan menggabungkan seluruh cabang pekerja aktif secara berurutan ke cabang utama. Pastikan proses pekerja telah selesai menulis berkas untuk mencegah konflik penggabungan.",
        ["Modal_Worktree_TargetRepo"] = "REPOSITORI TARGET",
        ["Modal_Worktree_BranchesToSynth"] = "CABANG UNTUK DISATUKAN",
        ["Modal_Worktree_BranchesQueued"] = "Cabang Pekerja yang Mengantre untuk Disatukan:",
        ["Modal_Worktree_Ready"] = "Siap Digabung",
        ["Modal_Worktree_AlwaysAsk"] = "Selalu minta konfirmasi sebelum penyatuan worktree (dapat diubah di Pengaturan)",

        // Skill Details Modal
        ["SkillModal_Location"] = "📁 Lokasi: ",
        ["SkillModal_PromptHeader"] = "Instruksi System Prompt SKILL.md:",

        // Splash Screen
        ["Splash_Title"] = "Google Antigravity CLI Swarm",
        ["Splash_Subtitle"] = "Orkestrator Sandbox Multi-Akun & Armada Telemetri",
        ["Splash_Initializing"] = "Menginisialisasi Telemetri Armada & Kuota...",
    };

    public string this[string key] => Get(key);

    public string Get(string key)
    {
        var dict = CurrentLanguage.Equals("id", StringComparison.OrdinalIgnoreCase) ? _id : _en;
        if (dict.TryGetValue(key, out var val)) return val;
        if (_en.TryGetValue(key, out var fallback)) return fallback;
        return key;
    }

    public void SetLanguage(string langCode)
    {
        CurrentLanguage = langCode.Equals("id", StringComparison.OrdinalIgnoreCase) ? "id" : "en";
        OnPropertyChanged(nameof(CurrentLanguage));
        OnPropertyChanged("Item[]");
    }
}
